# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_dte',
            new_name='published_date',
        ),
    ]
